/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

import java.awt.Graphics;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

//import managers.ManagerFactura;
/**
 *
 * @author Usuario
 */
public class Principal extends javax.swing.JFrame {

    DefaultTableModel modeloProveedor;
    int filas;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        modeloProveedor = new DefaultTableModel();
        modeloProveedor.addColumn("ID");
        modeloProveedor.addColumn("Nombre");
        modeloProveedor.addColumn("Cantidad");
        this.tblCliente.setModel(modeloProveedor);

        String[] datos = new String[6];

        this.cnbxClientes.removeAllItems();
        try {
            Connection con = DriverManager.getConnection("jdbc:postgresql://localhost:5432/conectar", "postgres", "123");
            Statement Sent = con.createStatement();
            ResultSet rs = Sent.executeQuery("select * from cliente");
            Statement leer = con.createStatement();
            ResultSet resultado = leer.executeQuery("select * from producto");
            while (resultado.next()) {
                datos[0] = resultado.getString(1);
                datos[1] = resultado.getString(2);
                datos[2] = resultado.getString(5);
                datos[3] = resultado.getString(4);
                datos[4] = resultado.getString(3);
                modeloProveedor.addRow(datos);
            }
            tblCliente.setModel(modeloProveedor);
            while (rs.next()) {
                this.cnbxClientes.addItem(rs.getString("nombre_cliente"));
             
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BProveedores = new javax.swing.JButton();
        BProductos = new javax.swing.JButton();
        BClientes = new javax.swing.JButton();
        BFacturacion = new javax.swing.JButton();
        BReporte = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRegistro = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        btnBuscarNombre = new javax.swing.JButton();
        txtIDBuscar = new javax.swing.JTextField();
        lblIdBuscar = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        lblTotalcarrito = new javax.swing.JLabel();
        txtIdProducto = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtPunitario = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtNombreProducto = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        cnbxClientes = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtNombreBuscar = new javax.swing.JTextField();
        lblNombreBuscar = new javax.swing.JLabel();
        btnIngresarProducto4 = new javax.swing.JButton();
        btnIngresarProducto5 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        btnIngresarProducto6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnBuscarID = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblCarrito = new javax.swing.JTable();
        btnConfirmar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCliente = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mundo Mascotas");

        jPanel1.setToolTipText("Mundo Mascotas");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BProveedores.setText("Proveedores");
        BProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BProveedoresActionPerformed(evt);
            }
        });
        jPanel1.add(BProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 140, 40));

        BProductos.setText("Reg. Productos/Inventario");
        BProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BProductosActionPerformed(evt);
            }
        });
        jPanel1.add(BProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, -1, 40));

        BClientes.setText("Clientes");
        BClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BClientesActionPerformed(evt);
            }
        });
        jPanel1.add(BClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 110, 40));

        BFacturacion.setText("Facturación");
        BFacturacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BFacturacionActionPerformed(evt);
            }
        });
        jPanel1.add(BFacturacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 350, 110, 30));

        BReporte.setText("Reporte de ganancias");
        BReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BReporteActionPerformed(evt);
            }
        });
        jPanel1.add(BReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 70, 170, 40));

        jButton5.setBackground(new java.awt.Color(204, 204, 204));
        jButton5.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icoDeletAllsmall.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 400, 40, -1));

        tblRegistro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número de venta", "Cliente", "Fecha", "Producto", "cantidad", "Total"
            }
        ));
        jScrollPane1.setViewportView(tblRegistro);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, 730, 250));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Tempus Sans ITC", 1, 60)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("MUNDO MASCOTAS");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 711, 45));

        btnBuscarNombre.setBackground(new java.awt.Color(204, 204, 204));
        btnBuscarNombre.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 12)); // NOI18N
        btnBuscarNombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icoBuscar.png"))); // NOI18N
        btnBuscarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarNombreActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscarNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 40, 40));

        txtIDBuscar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(txtIDBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 159, -1));

        lblIdBuscar.setBackground(new java.awt.Color(153, 153, 153));
        lblIdBuscar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblIdBuscar.setForeground(new java.awt.Color(255, 255, 255));
        lblIdBuscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIdBuscar.setText("ID");
        jPanel1.add(lblIdBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 105, 23));

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Agregar productos a la venta");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, 247, 23));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-7, 124, 1360, 10));

        jLabel10.setBackground(new java.awt.Color(153, 153, 153));
        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("ID");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 105, 23));

        lblTotalcarrito.setBackground(new java.awt.Color(153, 153, 153));
        lblTotalcarrito.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        lblTotalcarrito.setForeground(new java.awt.Color(0, 153, 51));
        lblTotalcarrito.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblTotalcarrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 610, 210, 90));

        txtIdProducto.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(txtIdProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, 159, -1));

        jLabel12.setBackground(new java.awt.Color(153, 153, 153));
        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("P/U");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, 105, 23));

        txtPunitario.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(txtPunitario, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 250, 159, -1));

        txtCantidad.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 280, 159, -1));

        jLabel13.setBackground(new java.awt.Color(153, 153, 153));
        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("CANTIDAD");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, 105, 23));

        jLabel15.setBackground(new java.awt.Color(153, 153, 153));
        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("NOMBRE");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, 105, 23));

        txtNombreProducto.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(txtNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 220, 159, -1));

        jButton8.setBackground(new java.awt.Color(204, 204, 204));
        jButton8.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 12)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icoCarrito.png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 320, -1, -1));

        cnbxClientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cnbxClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnbxClientesActionPerformed(evt);
            }
        });
        jPanel1.add(cnbxClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 220, 220, 28));

        jLabel17.setBackground(new java.awt.Color(153, 153, 153));
        jLabel17.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Seleccione");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 190, 130, -1));

        jLabel18.setBackground(new java.awt.Color(153, 153, 153));
        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("o");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 260, 40, 20));

        jLabel19.setBackground(new java.awt.Color(153, 153, 153));
        jLabel19.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("HISTORIAL DE VENTAS");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, 320, -1));

        txtNombreBuscar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtNombreBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombreBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 159, -1));

        lblNombreBuscar.setBackground(new java.awt.Color(153, 153, 153));
        lblNombreBuscar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblNombreBuscar.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreBuscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreBuscar.setText("NOMBRE");
        jPanel1.add(lblNombreBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 105, 23));

        btnIngresarProducto4.setBackground(new java.awt.Color(204, 204, 204));
        btnIngresarProducto4.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 12)); // NOI18N
        btnIngresarProducto4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icoEnviarDatos.png"))); // NOI18N
        btnIngresarProducto4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarProducto4ActionPerformed(evt);
            }
        });
        jPanel1.add(btnIngresarProducto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 50, 40));

        btnIngresarProducto5.setBackground(new java.awt.Color(204, 204, 204));
        btnIngresarProducto5.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 12)); // NOI18N
        btnIngresarProducto5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icoRefrescar.png"))); // NOI18N
        btnIngresarProducto5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarProducto5ActionPerformed(evt);
            }
        });
        jPanel1.add(btnIngresarProducto5, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 220, -1, 30));

        jLabel21.setBackground(new java.awt.Color(153, 153, 153));
        jLabel21.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(204, 204, 204));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Buscar en inventario por:");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 201, 23));

        btnIngresarProducto6.setBackground(new java.awt.Color(204, 204, 204));
        btnIngresarProducto6.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 12)); // NOI18N
        btnIngresarProducto6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icoRefrescar.png"))); // NOI18N
        btnIngresarProducto6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarProducto6ActionPerformed(evt);
            }
        });
        jPanel1.add(btnIngresarProducto6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 50, 40));

        jButton1.setText("Nombre");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, -1, -1));

        jButton2.setText("ID");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 70, -1));

        btnBuscarID.setBackground(new java.awt.Color(204, 204, 204));
        btnBuscarID.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 12)); // NOI18N
        btnBuscarID.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icoBuscar.png"))); // NOI18N
        btnBuscarID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarIDActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscarID, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 40, 40));

        tblCarrito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Cantidad", "v/u"
            }
        ));
        tblCarrito.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblCarritoKeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(tblCarrito);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 440, 270, 250));

        btnConfirmar.setBackground(new java.awt.Color(204, 204, 204));
        btnConfirmar.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        btnConfirmar.setText("CONFIRMAR");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });
        jPanel1.add(btnConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 370, 246, 39));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/limpiar.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 390, 50, 40));

        jLabel22.setBackground(new java.awt.Color(153, 153, 153));
        jLabel22.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Cliente o beneficiario");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 160, 247, 20));

        jLabel23.setBackground(new java.awt.Color(153, 153, 153));
        jLabel23.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(204, 204, 204));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Eliminar Todo");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 380, 120, 20));

        jLabel16.setBackground(new java.awt.Color(153, 153, 153));
        jLabel16.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("CARRITO");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 400, 120, 30));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icoSacarDelCarrito.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 390, 50, 40));

        jButton11.setBackground(new java.awt.Color(204, 204, 204));
        jButton11.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 12)); // NOI18N
        jButton11.setText("Registrar ");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 290, -1, -1));

        tblCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        tblCliente.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                tblClienteComponentRemoved(evt);
            }
        });
        tblCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClienteMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblCliente);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 240, 250));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1072345.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 770));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BProveedoresActionPerformed
        Proveedor P = new Proveedor();
        P.setVisible(true);
    }//GEN-LAST:event_BProveedoresActionPerformed

    private void BReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BReporteActionPerformed
        Reporte P = new Reporte();
        P.setVisible(true);
    }//GEN-LAST:event_BReporteActionPerformed

    private void BProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BProductosActionPerformed
        Producto P = null;
        try {
            P = new Producto();
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        P.setVisible(true);
    }//GEN-LAST:event_BProductosActionPerformed

    private void BClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BClientesActionPerformed
        RClientes R = new RClientes();
        R.setVisible(true);
    }//GEN-LAST:event_BClientesActionPerformed

    private void BFacturacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BFacturacionActionPerformed
        // TODO add your handling code here:
        Factura F = new Factura();
        F.setVisible(true);
    }//GEN-LAST:event_BFacturacionActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnBuscarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarNombreActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarNombreActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void txtNombreBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreBuscarActionPerformed

    private void btnIngresarProducto4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarProducto4ActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_btnIngresarProducto4ActionPerformed

    private void btnIngresarProducto5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarProducto5ActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_btnIngresarProducto5ActionPerformed

    private void btnIngresarProducto6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarProducto6ActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_btnIngresarProducto6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnBuscarIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarIDActionPerformed

    private void tblCarritoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblCarritoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tblCarritoKeyPressed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed

        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void cnbxClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnbxClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnbxClientesActionPerformed

    private void tblClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClienteMouseClicked
        // TODO add your handling code here:
        int seleccion = tblCliente.getSelectedRow();
        txtIdProducto.setText(tblCliente.getValueAt(seleccion, 0).toString());
        txtNombreProducto.setText(tblCliente.getValueAt(seleccion, 1).toString());
        filas = seleccion;
    }//GEN-LAST:event_tblClienteMouseClicked

    private void tblClienteComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_tblClienteComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_tblClienteComponentRemoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BClientes;
    private javax.swing.JButton BFacturacion;
    private javax.swing.JButton BProductos;
    private javax.swing.JButton BProveedores;
    private javax.swing.JButton BReporte;
    private javax.swing.JButton btnBuscarID;
    private javax.swing.JButton btnBuscarNombre;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnIngresarProducto4;
    private javax.swing.JButton btnIngresarProducto5;
    private javax.swing.JButton btnIngresarProducto6;
    private javax.swing.JComboBox<String> cnbxClientes;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblIdBuscar;
    private javax.swing.JLabel lblNombreBuscar;
    private javax.swing.JLabel lblTotalcarrito;
    private javax.swing.JTable tblCarrito;
    private javax.swing.JTable tblCliente;
    private javax.swing.JTable tblRegistro;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtIDBuscar;
    private javax.swing.JTextField txtIdProducto;
    private javax.swing.JTextField txtNombreBuscar;
    private javax.swing.JTextField txtNombreProducto;
    private javax.swing.JTextField txtPunitario;
    // End of variables declaration//GEN-END:variables
}
