/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.eclipse.persistence.platform.database.PostgreSQLPlatform;

/**
 *
 * @author Usuario
 */
public class Producto extends javax.swing.JFrame {

    DefaultTableModel modeloProducto;
    int filas;

    /**
     * Creates new form Principal
     */
    public Producto() throws SQLException {
        initComponents();

        modeloProducto = new DefaultTableModel();
        modeloProducto.addColumn("ID");
        modeloProducto.addColumn("Nombre producto");
        modeloProducto.addColumn("Proveedor");
        modeloProducto.addColumn("P. Compra unitario");
        modeloProducto.addColumn("P. Venta unitario");
        modeloProducto.addColumn("Cantidad");
        this.tblProducto.setModel(modeloProducto);

        this.cbxProveedorProducto.removeAllItems();
        String[] datos = new String[6];
        try {
            Connection con = DriverManager.getConnection("jdbc:postgresql://localhost:5432/conectar", "postgres", "123");
            Statement Sent = con.createStatement();
            ResultSet rs = Sent.executeQuery("select * from proveedor");
            while (rs.next()) {
                this.cbxProveedorProducto.addItem(rs.getString("nombre_proveedor"));
            }
            ResultSet resultado = Sent.executeQuery("select * from producto");
            while (resultado.next()) {
                datos[0] = resultado.getString(1);
                datos[1] = resultado.getString(2);
                datos[2] = resultado.getString(3);
                datos[3] = resultado.getString(4);
                datos[4] = resultado.getString(5);
                datos[5] = resultado.getString(6);
                modeloProducto.addRow(datos);
            }
            tblProducto.setModel(modeloProducto);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCantidadProducto = new javax.swing.JTextField();
        txtRucProducto = new javax.swing.JTextField();
        txtPCompraProducto = new javax.swing.JTextField();
        txtDescuento = new javax.swing.JTextField();
        txtNombreProducto = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnEliminarProveedor = new javax.swing.JButton();
        btnInsertarProveedor = new javax.swing.JButton();
        btnActualizarProducto = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cbxProveedorProducto = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProducto = new javax.swing.JTable();
        txtPVentaProducto = new javax.swing.JTextField();
        jToggleButton2 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Proveedores");

        jPanel1.setToolTipText("Proveedores");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("REGISTRO DE PRODUCTO");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        jLabel8.setBackground(new java.awt.Color(153, 153, 153));
        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Cantidad");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        jLabel9.setBackground(new java.awt.Color(153, 153, 153));
        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("ID");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        txtCantidadProducto.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtCantidadProducto.setText("30");
        jPanel1.add(txtCantidadProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 240, 30));

        txtRucProducto.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtRucProducto.setText("10");
        txtRucProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRucProductoActionPerformed(evt);
            }
        });
        jPanel1.add(txtRucProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 240, 30));

        txtPCompraProducto.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtPCompraProducto.setText("20.50");
        txtPCompraProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPCompraProductoActionPerformed(evt);
            }
        });
        jPanel1.add(txtPCompraProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 240, 30));

        txtDescuento.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtDescuento.setText("15");
        txtDescuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescuentoActionPerformed(evt);
            }
        });
        jPanel1.add(txtDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 240, 20));

        txtNombreProducto.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtNombreProducto.setText("cama perro");
        txtNombreProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreProductoActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 240, 30));

        jLabel11.setBackground(new java.awt.Color(153, 153, 153));
        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Proveedor");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, 20));

        jLabel12.setBackground(new java.awt.Color(153, 153, 153));
        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("% Ganancia");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        jLabel13.setBackground(new java.awt.Color(153, 153, 153));
        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Nombre Producto");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        btnEliminarProveedor.setBackground(new java.awt.Color(204, 204, 204));
        btnEliminarProveedor.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 12)); // NOI18N
        btnEliminarProveedor.setText("ELIMINAR PRODUCTO");
        btnEliminarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProveedorActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));

        btnInsertarProveedor.setBackground(new java.awt.Color(204, 204, 204));
        btnInsertarProveedor.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 12)); // NOI18N
        btnInsertarProveedor.setText("INGRESAR DATOS");
        btnInsertarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarProveedorActionPerformed(evt);
            }
        });
        jPanel1.add(btnInsertarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, -1, -1));

        btnActualizarProducto.setBackground(new java.awt.Color(204, 204, 204));
        btnActualizarProducto.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 12)); // NOI18N
        btnActualizarProducto.setText("ACTUALIZAR PRODUCTO");
        btnActualizarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarProductoActionPerformed(evt);
            }
        });
        jPanel1.add(btnActualizarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, -1, -1));

        jLabel14.setBackground(new java.awt.Color(153, 153, 153));
        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("P. Compra unitario");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, 30));

        jLabel15.setBackground(new java.awt.Color(153, 153, 153));
        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("P. Venta unitario");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        cbxProveedorProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxProveedorProductoActionPerformed(evt);
            }
        });
        jPanel1.add(cbxProveedorProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 240, -1));

        tblProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        tblProducto.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tblProductoAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tblProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblProducto);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 610, 110));

        txtPVentaProducto.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtPVentaProducto.setText("24.25");
        txtPVentaProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPVentaProductoActionPerformed(evt);
            }
        });
        jPanel1.add(txtPVentaProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 240, 20));

        jToggleButton2.setBackground(new java.awt.Color(255, 0, 0));
        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/atras.png"))); // NOI18N
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 34));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoHoy.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreProductoActionPerformed

    private void txtPCompraProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPCompraProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPCompraProductoActionPerformed

    private void btnEliminarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProveedorActionPerformed

        // TODO add your handling code here:
        if (tblProducto.getSelectedRow() >= 0) {
            DefaultTableModel tm = (DefaultTableModel) tblProducto.getModel();
            int rpta = JOptionPane.showConfirmDialog(this, "Deseas eliminar el Producto seleccionado", "", JOptionPane.INFORMATION_MESSAGE);
            if (rpta == JOptionPane.YES_OPTION) {
                tm.removeRow(tblProducto.getSelectedRow());
            }
        } else {
            JOptionPane.showConfirmDialog(this, "Seleccione el Producto que desea eliminar", "", JOptionPane.WARNING_MESSAGE);

        }

    }//GEN-LAST:event_btnEliminarProveedorActionPerformed

    private void btnInsertarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarProveedorActionPerformed
        // TODO add your handling code here:

        String[] info = new String[6];
        info[0] = txtRucProducto.getText();
        info[1] = txtNombreProducto.getText();
        info[2] = txtPCompraProducto.getText();
        info[3] = txtPVentaProducto.getText();
        info[4] = txtCantidadProducto.getText();
        info[5] = (String) cbxProveedorProducto.getSelectedItem();
        modeloProducto.addRow(info);

        txtRucProducto.setText("");
        txtNombreProducto.setText("");
        cbxProveedorProducto.setSelectedItem(info);
        txtPCompraProducto.setText("");
        txtPVentaProducto.setText("");
        txtCantidadProducto.setText("");
        txtDescuento.setText("");


    }//GEN-LAST:event_btnInsertarProveedorActionPerformed

    private void btnActualizarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarProductoActionPerformed
        // TODO add your handling code here:
        String[] info = new String[6];
        info[0] = txtRucProducto.getText();
        info[1] = txtNombreProducto.getText();
//        info[2] = cbxProveedorProducto.getText();
        info[3] = txtPCompraProducto.getText();
        info[4] = txtPVentaProducto.getText();
        info[5] = txtCantidadProducto.getText();
        for (int i = 0; i < tblProducto.getColumnCount(); i++) {
            modeloProducto.setValueAt(info[i], filas, i);
        }
    }//GEN-LAST:event_btnActualizarProductoActionPerformed

    private void cbxProveedorProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxProveedorProductoActionPerformed
        // TODO add your handling code here:
       


    }//GEN-LAST:event_cbxProveedorProductoActionPerformed

    private void tblProductoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tblProductoAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tblProductoAncestorAdded

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void txtRucProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRucProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRucProductoActionPerformed

    private void txtPVentaProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPVentaProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPVentaProductoActionPerformed

    private void tblProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductoMouseClicked
        // TODO add your handling code here:
        int seleccion = tblProducto.getSelectedRow();
        txtRucProducto.setText(tblProducto.getValueAt(seleccion, 0).toString());
        txtNombreProducto.setText(tblProducto.getValueAt(seleccion, 1).toString());
//        txtApellidoCliente.setText(tblProducto.getValueAt(seleccion, 2).toString());
        txtPCompraProducto.setText(tblProducto.getValueAt(seleccion, 3).toString());
        txtPVentaProducto.setText(tblProducto.getValueAt(seleccion, 4).toString());
        txtCantidadProducto.setText(tblProducto.getValueAt(seleccion, 5).toString());
        filas = seleccion;
    }//GEN-LAST:event_tblProductoMouseClicked

    private void txtDescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescuentoActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);

    }//GEN-LAST:event_txtDescuentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Producto().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Producto.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarProducto;
    private javax.swing.JButton btnEliminarProveedor;
    private javax.swing.JButton btnInsertarProveedor;
    private javax.swing.JComboBox<String> cbxProveedorProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JTable tblProducto;
    private javax.swing.JTextField txtCantidadProducto;
    private javax.swing.JTextField txtDescuento;
    private javax.swing.JTextField txtNombreProducto;
    private javax.swing.JTextField txtPCompraProducto;
    private javax.swing.JTextField txtPVentaProducto;
    private javax.swing.JTextField txtRucProducto;
    // End of variables declaration//GEN-END:variables
}
