package Principal;

import java.awt.Graphics;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Usuario
 */
public class Proveedor extends javax.swing.JFrame {
     DefaultTableModel modeloProveedor;
     int filas;

    /**
     * Creates new form Principal
     */
    public Proveedor() {
       initComponents();
        modeloProveedor = new DefaultTableModel();
        modeloProveedor.addColumn("Ruc/Cédula");
        modeloProveedor.addColumn("Nombre");
        modeloProveedor.addColumn("Teléfono");
        modeloProveedor.addColumn("Correo");
        modeloProveedor.addColumn("Producto");
        this.tblProveedor.setModel(modeloProveedor);
        
        String[] datos = new String[5];

        try {
            Connection con = DriverManager.getConnection("jdbc:postgresql://localhost:5432/conectar", "postgres", "123");
            Statement leer = con.createStatement();
            ResultSet resultado = leer.executeQuery("select * from proveedor");
            while (resultado.next()) {
                datos[0] = resultado.getString(1);
                datos[1] = resultado.getString(2);
                datos[2] = resultado.getString(3);
                datos[3] = resultado.getString(4);
                datos[4] = resultado.getString(5);
                modeloProveedor.addRow(datos);
            }
            tblProveedor.setModel(modeloProveedor);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e+"Error");
        }

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtProductoProveedor = new javax.swing.JTextField();
        txtRucProveedor = new javax.swing.JTextField();
        txtCorreoProveedor = new javax.swing.JTextField();
        txtTelefonoProveedor = new javax.swing.JTextField();
        txtNombreProveedor = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnEliminarProveedor = new javax.swing.JButton();
        btnInsertarProveedor = new javax.swing.JButton();
        btnActualizarProveedor = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProveedor = new javax.swing.JTable();
        jToggleButton2 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Proveedores");

        jPanel1.setToolTipText("Proveedores");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("REGISTRO DE PROVEEDORES");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        jLabel8.setBackground(new java.awt.Color(153, 153, 153));
        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Producto");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, -1, -1));

        jLabel9.setBackground(new java.awt.Color(153, 153, 153));
        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Ruc / Cédula");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, -1, -1));

        txtProductoProveedor.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtProductoProveedor.setText("cama de perro");
        jPanel1.add(txtProductoProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 240, 20));

        txtRucProveedor.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtRucProveedor.setText("1004536783");
        jPanel1.add(txtRucProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 240, 20));

        txtCorreoProveedor.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtCorreoProveedor.setText("marceloandrade@gmail.com");
        txtCorreoProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoProveedorActionPerformed(evt);
            }
        });
        jPanel1.add(txtCorreoProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 240, 20));

        txtTelefonoProveedor.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtTelefonoProveedor.setText("0981234564");
        jPanel1.add(txtTelefonoProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 240, 20));

        txtNombreProveedor.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtNombreProveedor.setText("Marcelo Andrade");
        txtNombreProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreProveedorActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombreProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 240, 20));

        jLabel11.setBackground(new java.awt.Color(153, 153, 153));
        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Correo");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, -1, 20));

        jLabel12.setBackground(new java.awt.Color(153, 153, 153));
        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Teléfono");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, -1, -1));

        jLabel13.setBackground(new java.awt.Color(153, 153, 153));
        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Nombre");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, -1, -1));

        btnEliminarProveedor.setBackground(new java.awt.Color(204, 204, 204));
        btnEliminarProveedor.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 12)); // NOI18N
        btnEliminarProveedor.setText("ELIMINAR PROVEEDOR");
        btnEliminarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProveedorActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 320, -1, -1));

        btnInsertarProveedor.setBackground(new java.awt.Color(204, 204, 204));
        btnInsertarProveedor.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 12)); // NOI18N
        btnInsertarProveedor.setText("INGRESAR DATOS");
        btnInsertarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarProveedorActionPerformed(evt);
            }
        });
        jPanel1.add(btnInsertarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, -1, -1));

        btnActualizarProveedor.setBackground(new java.awt.Color(204, 204, 204));
        btnActualizarProveedor.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 12)); // NOI18N
        btnActualizarProveedor.setText("ACTUALIZAR PROVEEDOR");
        btnActualizarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarProveedorActionPerformed(evt);
            }
        });
        jPanel1.add(btnActualizarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, -1, -1));

        tblProveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tblProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProveedorMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblProveedor);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 640, 110));

        jToggleButton2.setBackground(new java.awt.Color(255, 0, 0));
        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/atras.png"))); // NOI18N
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 34));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/dog-bed-1.jpg"))); // NOI18N
        jLabel1.setText("                                                                                                                                                                                                                                                                             ,,,,,,,,");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreProveedorActionPerformed

    private void txtCorreoProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoProveedorActionPerformed

    private void btnEliminarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProveedorActionPerformed
        // TODO add your handling code here:
        if (tblProveedor.getSelectedRow() >= 0) {
            DefaultTableModel tm = (DefaultTableModel)tblProveedor.getModel();
            int rpta = JOptionPane.showConfirmDialog(this, "Deseas eliminar el Proveedor seleccionado","",JOptionPane.INFORMATION_MESSAGE);
            if (rpta == JOptionPane.YES_OPTION) {
                tm.removeRow(tblProveedor.getSelectedRow());
            }
        }else{
            JOptionPane.showConfirmDialog(this, "Seleccione el Proveedor que desea eliminar","",JOptionPane.WARNING_MESSAGE);
        }        

    }//GEN-LAST:event_btnEliminarProveedorActionPerformed

    private void btnInsertarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarProveedorActionPerformed
        // TODO add your handling code here:
        String[] info = new String[5];
        info[0]=txtRucProveedor.getText();
        info[1]=txtNombreProveedor.getText();
        info[2]=txtTelefonoProveedor.getText();
        info[3]=txtCorreoProveedor.getText();
        info[4]=txtProductoProveedor.getText();
        modeloProveedor.addRow(info);
        
        txtRucProveedor.setText("");
        txtNombreProveedor.setText("");
        txtTelefonoProveedor.setText("");
        txtCorreoProveedor.setText("");
        txtProductoProveedor.setText("");       
    }//GEN-LAST:event_btnInsertarProveedorActionPerformed

    private void btnActualizarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarProveedorActionPerformed
        // TODO add your handling code here:
        String[] info = new String[5];
        info[0] = txtRucProveedor.getText();
        info[1] = txtNombreProveedor.getText();
        info[2] = txtTelefonoProveedor.getText();
        info[3] = txtCorreoProveedor.getText();
        info[4] = txtProductoProveedor.getText();

        for (int i = 0; i < tblProveedor.getColumnCount(); i++) {
            modeloProveedor.setValueAt(info[i], filas, i);
        }
        
    }//GEN-LAST:event_btnActualizarProveedorActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void tblProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProveedorMouseClicked
        // TODO add your handling code here:
         int seleccion = tblProveedor.getSelectedRow();
        txtRucProveedor.setText(tblProveedor.getValueAt(seleccion, 0).toString());
        txtNombreProveedor.setText(tblProveedor.getValueAt(seleccion, 1).toString());
        txtTelefonoProveedor.setText(tblProveedor.getValueAt(seleccion, 2).toString());
        txtCorreoProveedor.setText(tblProveedor.getValueAt(seleccion, 3).toString());
        txtProductoProveedor.setText(tblProveedor.getValueAt(seleccion, 4).toString());
        filas = seleccion;

    }//GEN-LAST:event_tblProveedorMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Proveedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarProveedor;
    private javax.swing.JButton btnEliminarProveedor;
    private javax.swing.JButton btnInsertarProveedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JTable tblProveedor;
    private javax.swing.JTextField txtCorreoProveedor;
    public static javax.swing.JTextField txtNombreProveedor;
    private javax.swing.JTextField txtProductoProveedor;
    private javax.swing.JTextField txtRucProveedor;
    private javax.swing.JTextField txtTelefonoProveedor;
    // End of variables declaration//GEN-END:variables
}
